// Copyright (c) 2014-2019 Coin Sciences Ltd
// AksyonChain code distributed under the GPLv3 license, see COPYING file.

#ifndef AKSYONCHAINVERSION_H
#define	AKSYONCHAINVERSION_H

#define AKSYONCHAIN_VERSION_MAJOR     1
#define AKSYONCHAIN_VERSION_MINOR     0
#define AKSYONCHAIN_VERSION_REVISION  0
#define AKSYONCHAIN_VERSION_STAGE     2
#define AKSYONCHAIN_VERSION_BUILD     2

#define AKSYONCHAIN_PROTOCOL_VERSION 10008
#define AKSYONCHAIN_PROTOCOL_SUPPORTED "10004 - 10008, 20001"


#ifndef STRINGIZE
#define STRINGIZE(X) DO_STRINGIZE(X)
#endif

#ifndef DO_STRINGIZE
#define DO_STRINGIZE(X) #X
#endif

#define AKSYONCHAIN_BUILD_DESC_WITH_SUFFIX(maj, min, rev, build, suffix) \
    DO_STRINGIZE(maj) "." DO_STRINGIZE(min) "." DO_STRINGIZE(rev) "." DO_STRINGIZE(build) "-" DO_STRINGIZE(suffix)

#define AKSYONCHAIN_BUILD_DESC_FROM_UNKNOWN(maj, min, rev, build) \
    DO_STRINGIZE(maj) "." DO_STRINGIZE(min) "." DO_STRINGIZE(rev) "." DO_STRINGIZE(build)


#define AKSYONCHAIN_BUILD_DESC "1.0 beta 2"
#define AKSYONCHAIN_BUILD_DESC_NUMERIC 10000202


#ifndef AKSYONCHAIN_BUILD_DESC
#ifdef BUILD_SUFFIX
#define AKSYONCHAIN_BUILD_DESC AKSYONCHAIN_BUILD_DESC_WITH_SUFFIX(AKSYONCHAIN_VERSION_MAJOR, AKSYONCHAIN_VERSION_MINOR, AKSYONCHAIN_VERSION_REVISION, AKSYONCHAIN_VERSION_BUILD, BUILD_SUFFIX)
#else
#define AKSYONCHAIN_BUILD_DESC AKSYONCHAIN_BUILD_DESC_FROM_UNKNOWN(AKSYONCHAIN_VERSION_MAJOR, AKSYONCHAIN_VERSION_MINOR, AKSYONCHAIN_VERSION_REVISION, AKSYONCHAIN_VERSION_BUILD)
#endif
#endif

#define AKSYONCHAIN_FULL_DESC(build, protocol) \
    "build " build " protocol " DO_STRINGIZE(protocol)


#ifndef AKSYONCHAIN_FULL_VERSION
#define AKSYONCHAIN_FULL_VERSION AKSYONCHAIN_FULL_DESC(AKSYONCHAIN_BUILD_DESC, AKSYONCHAIN_PROTOCOL_VERSION)
#endif


#define AKSYONCHAIN_VERSION_CODE_PROTOCOL_THIS              0
#define AKSYONCHAIN_VERSION_CODE_PROTOCOL_MIN               1
#define AKSYONCHAIN_VERSION_CODE_PROTOCOL_MIN_DOWNGRADE     2
#define AKSYONCHAIN_VERSION_CODE_PROTOCOL_MIN_NO_DOWNGRADE  3
#define AKSYONCHAIN_VERSION_CODE_PROTOCOL_FOR_RELEVANCE     4
#define AKSYONCHAIN_VERSION_CODE_BUILD                     16
#define AKSYONCHAIN_VERSION_CODE_MIN_VALID               1000

#endif	/* AKSYONCHAINVERSION_H */

